version: '3.4'

services:
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    restart: always
    env_file: ./.env
    ports:
      - 1433:1433
    environment:
      - MSSQL_SA_PASSWORD=1qaz!QAZ
      - ACCEPT_EULA=Y
    expose:
      - '1433'
    networks:
      - backend      

  medicalsystem.api:
    image: caiotmello/medicalsystemapi
    build:
      context: .
      dockerfile: MedicalSystem.Api/Dockerfile
    restart: always
    env_file: ./.env
    environment:
     - DB_HOST=sqlserverdb
     - DB_USER=sa
     - DB_PASSWORD=1qaz!QAZ
     - DB_NAME=MedicalSystem
     - DB_PORT=1433
    ports:
      - 8888:8080
      - 8889:8081
    networks:
      - backend
    depends_on:
      - sqlserverdb
networks:
  backend:
    driver: 'bridge'