name: Build and Deploy Application to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: "rg_medicalsystem"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

       # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test ./src/back/MedicalSystem.Test/MedicalSystem.Test.csproj

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: MedicalSystem Api - Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src/back
          file: ./src/back/MedicalSystem.Api/Dockerfile
          push: true
          tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/medicalsystemapi:v${{ github.run_number }}
           ${{ secrets.DOCKERHUB_USERNAME }}/medicalsystemapi:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checks out the repository this file is in
      - uses: actions/checkout@v3
     
     # Logs in with your Azure credentials
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1.4.6
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            
     # Deploy application to Azure Web App
      - name: Deploy Docker Compose to Azure Web App
        run: |
          az webapp config container set --resource-group ${{ env.RESOURCE_GROUP }} --name medicalsystemfiap --multicontainer-config-type compose --multicontainer-config-file ./src/back/docker-compose.yml
        env:
          AZURE_WEBAPP_NAME: 'medicalsystemfiap'
          AZURE_RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
