name: Build and Deploy Application to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CLUSTER_NAME: "techchallenge05"
  RESOURCE_GROUP: "rg_techchallenge05"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

       # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test ./src/back/MedicalSystem.Test.csproj

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
      - name: MedicalSystem Api - Build and push Docker images
        uses: docker/build-push-action@v4.1.1
        with:
          context: ./src/back
          file: ./src/back/MedicalSystem.Api/Dockerfile
          push: true
          tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/medicalsystemapi:v${{ github.run_number }}
           ${{ secrets.DOCKERHUB_USERNAME }}/medicalsystemapi:latest
